<script>
  export default {
    created () {
    },
    computed: {
    },
    methods: {
      submit: function (e) {
        this.$validator.validateAll()
        if (this.errors.any()) {
          return false
        }
      }
    }
  }
</script>
<style></style>
<template>
    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">文章管理</h3>
        </div>
        <div class="box-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-1 control-label"></label>
                    <div class="col-sm-3">
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th class="col-md-5">文章标题</th>
                        <th class="col-md-2">所属栏目</th>
                        <th class="col-md-2">创建时间</th>
                        <th class="col-md-3">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                    <tr>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                        <td>Everything</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th class="col-md-5">文章标题</th>
                        <th class="col-md-2">所属栏目</th>
                        <th class="col-md-2">创建时间</th>
                        <th class="col-md-3">操作</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="box-footer">
            <button class="btn btn-primary" :disabled="errors.any()" @click="submit">保存</button>
        </div>
    </div>
</template>